version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    hostname: mongo

  data-service:
    image: ticket-0.0.1:latest
    links:
      - mongo
#    environment:
#      - SPRING_DATA_MONGODB_HOST=mongo
    depends_on:
      - mongo
    ports:
      - "8080:8080"