version: '3'
services:
  mongo:
    container_name: mongo_finartz
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    hostname: mongo

  data-service:
    image: finartz:latest
    links:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    depends_on:
      - mongo
      - redis
    ports:
      - "8080:8080"