service:
  name: Finartz Ticket Api

server:
  port: 8080
  servlet:
    context-path: /finartz

springfox:
  documentation:
    swagger-ui:
      enabled: true
    swagger:
      enabled: true
      v2:
        path: /finartz/swagger-ui.html